### PR TITLE
Default slider value fix

### LINKED ISSUE #979: no visible nodes for smaller networks at default slider value
## Environment info

- interactions app

## Current (buggy) behaviour

- initial network display for smaller networks has no visible nodes with default slider value

Right after loading

image

After adjusting slider

image

### PR DESCRIPTION
**Pull request by MichaelWrana**
Fixes #979

### CODE REVIEW

File: src/client/features/interactions/interactions-menu.js [hunk 1]
```diff
@@ -83,11 +83,17 @@ class InteractionsMenu extends React.Component {
...
     let { BINDING, PHOSPHORYLATION, EXPRESSION } = INTERACTION_TYPES;
 
-
     let hasPhosphorylations = hasType(cy, PHOSPHORYLATION);
     let hasExpressions = hasType(cy, EXPRESSION);
     let hasBindings = hasType(cy, BINDING);
 
+    let defaultSliderValue = 0;
+    const numberOfNodes = this.getMetricSortedNodes().length;
+    if(numberOfNodes < 25)
```
Comment (d2fong) [inline src/client/features/interactions/interactions-menu.js]: Follow common code style; add curly braces after if and else statements.
